#include "shell.h"

QueueHandle_t xRecvQueue;
static uint8_t inputBuf[SHELL_INPUT_BUF_LEN];
static uint8_t *inputBufPtr;
static uint8_t outputBuf[SHELL_RECV_QUEUE_LEN];
const char commandPrompt[] = "\033[1;32mshell# \033[0m";

void uart_rx_handler() {
    BaseType_t xHigherPriorityTaskWoken = pdFALSE;
    while (uart_is_readable(UART_PERI)) {
        uint8_t ch = uart_getc(UART_PERI);
        xQueueSendFromISR(xRecvQueue, &ch, &xHigherPriorityTaskWoken);
    }
    portYIELD_FROM_ISR(xHigherPriorityTaskWoken);
}

void shell_init() {
    uart_init(UART_PERI, UART_BAUDRATE);

    // initialize uart
    gpio_set_function(0, GPIO_FUNC_UART);
    gpio_set_function(1, GPIO_FUNC_UART);
    irq_set_exclusive_handler(UART_IRQ, uart_rx_handler);
    irq_set_enabled(UART_IRQ, true);
    uart_set_irq_enables(UART_PERI, true, false); // UARTRXINT on, UARTTXINT off

    // initialize buffers
    inputBufPtr = inputBuf;
    xRecvQueue = xQueueCreate(SHELL_RECV_QUEUE_LEN, sizeof(uint8_t));
    configASSERT(xRecvQueue);

    // initialize commands
    register_commands();

    printf("welcome to rp2350 freertos shell \r\n");
    printf("%s", commandPrompt);
}

void shell_execute() {
    BaseType_t xMoreDataToFollow;
    char ch = 0;
    char inputIndex = 0;

    for (;;) {
        // wait in blocked state until a character is received by the queue
        xQueueReceive(xRecvQueue, &ch, portMAX_DELAY);

        if (ch == '\n') {
            // a new line character is received, so the input command string is complete and can be processed. 
            printf("\r\n");
            do {
                xMoreDataToFollow = FreeRTOS_CLIProcessCommand(inputBuf, outputBuf, SHELL_RECV_QUEUE_LEN);
                printf("%s", outputBuf);
            } while (xMoreDataToFollow != pdFALSE);
            // all the strings generated by the input command have been sent. Processing of the
            // command is complete. Clear the input string ready to receive the next command.
            inputIndex = 0;
            memset(inputBuf, 0x00, SHELL_INPUT_BUF_LEN);
            printf("%s", commandPrompt);
        } else {
            if (ch == '\r') {
                // ignore carriage returns
            } else if (ch == '\b') {
                // backspace was pressed. erase the last character in the input buffer if there are any
                if (inputIndex > 0) {
                    inputIndex--;
                    inputBuf[inputIndex] = '\0';
                    printf("\b \b"); // device echo of removing a character 
                }
            } else {
                // some character was entered that was not a newline, backspace, or carriage return.
                // we accept this character as part of the input
                if (inputIndex < SHELL_INPUT_BUF_LEN) {
                    inputBuf[inputIndex] = ch;
                    inputIndex++;
                    printf("%c", ch); // device echo back to the terminal emulator
                }
            }
        }
    }
}